### ISSUE TITLE
Home screen widget black box over background

### ISSUE THREAD

**Issue by twdent** [zaminiti/DayCount---Bugs#12]
The homescreen widgets have a a black box behind the text, in the region where the day count, days until, and countdown topic, are visible. 

The background is still visible around the borders of this

**Comment by boclaire** [comment]
I have the same problem. Started yesterday

**Comment by zaminiti** [comment]
Hey there, could you both let me know which iOS version you have on your devices? Thanks!

**Comment by twdent** [comment]
16.1.1 on iPhone 12 for me

**Comment by boclaire** [comment]
Mine is on IOS 16.3.1

Op vr 23 feb. 2024 om 17:35 schreef twdent ***@***.***>

> 16.1.1 on iPhone 12 for me
>

**Comment by zaminiti** [comment]
I do believe it's a bug that appearing only on devices which are still on iOS 16.x. If you don't wish to upgrade to iOS 17 for whatever reason, then we'll try to release an update soon with a fix. Otherwise, the best (and fastest) solution is to upgrade your device to iOS 17. Hope this helps!

**Comment by boclaire** [comment]
Updated to IOS 17 and my personal screen is back. Thank you for the support Verstuurd vanaf mijn iPhoneOp 25 feb 2024 om 06:49 heeft zaminiti ***@***.***> het volgende geschreven:﻿
I do believe it's a bug that appearing only on devices which are still on iOS 16.x. If you don't wish to upgrade to iOS 17 for whatever reason, then we'll try to release an update soon with a fix. Otherwise, the best (and fastest) solution is to upgrade your device to iOS 17. Hope this helps!

**Comment by twdent** [comment]
Worked for me too, thanks

**Comment by zaminiti** [comment]
Awesome! I'm glad that it helped. Thank you both for using DayCount, I appreciate it!
